### ISSUE TITLE
Failed to load External library between two projects in one solution

### ISSUE THREAD

**Issue by ghost** [CodeConnect/AliveFeedback#79]
I'm using a external library in two projects, when i start Alive in some part of one project it works fine but then i stop it and i try to start alive on my other project, then i got something like this "Unhandled FileNotFounfException: Could not load file or assembly ...."

so if i want to make it working i need to close the Solution and open it again every time i want to test something between the two projects.

**Comment by AmadeusW** [comment]
Hi @Alcatraz3222 thank you for reaching out.
We've had a similar issue recently and fixed it. An update is on the way, I'll let you know when it's out (expect it this weekend or on Monday).

**Comment by JoshVarty** [comment]
Hey @Alcatraz3222 I've just pushed an update to our extension we're hoping will fix your issue. You'll probably have to restart VS for it to take effect. Once you've done that please let us know if it has fixed your issue.

**Comment by ghost** [comment]
Hi, i still can't use it on both projects at once but this time is showing another error "Evaluation of <MethodName> was interrumped due to errors."

**Comment by AmadeusW** [comment]
Is one of the projects a portable class library, or targets a mobile device?
The full error message should be located in the **Output** window:
![screenshot of the output window](https://i.gyazo.com/8cc8e1d8de640742593c20fd269565f4.png)

Please tell us what you see there. Thank you!

**Comment by ghost** [comment]
They both are Console Application

![qpya1iq](https://cloud.githubusercontent.com/assets/10264083/12538978/35ce3fde-c2e8-11e5-83c1-3dc096c79ba0.png)

**Comment by JoshVarty** [comment]
Is the assembly it's complaining about a referenced DLL or is it a project in your solution?

**Comment by ghost** [comment]
it's a project in my solution, i can send you a sample code if you want to

**Comment by ghost** [comment]
Okay, i found something that may help you.

The first time i start Alive in one project all the references are copied to the correct path on Temp, but when i attempt to try the second project, references are not copied to any folder, neither the first project folder.

**Comment by JoshVarty** [comment]
Sure, you can show me the repo (if it's open source) or you can email it to me at: josh@comealive.io and I'll take a look at it as well.

**Comment by ghost** [comment]
Sent you a Email, hoping this get fixed soon :)

**Comment by JoshVarty** [comment]
Thanks, I've repro-ed this. I don't anticipate this being super hard to fix, so I'll work on a fix tonight and will have a fix available for release tomorrow.

**Comment by JoshVarty** [comment]
This should be good to go now. I've pushed out an update and double checked that everything behaved properly within the sample project you provided. If you have any problems feel free to re-open and let us know.

Note that you may need to restart VS for the new version to kick in.
